import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const neighborhoods = [
  // Manhattan
  { name: 'Battery Park City', borough: 'Manhattan', slug: 'battery-park-city' },
  { name: 'Tribeca', borough: 'Manhattan', slug: 'tribeca' },
  { name: 'SoHo', borough: 'Manhattan', slug: 'soho' },
  { name: 'Chinatown', borough: 'Manhattan', slug: 'chinatown' },
  { name: 'Little Italy', borough: 'Manhattan', slug: 'little-italy' },
  { name: 'Lower East Side', borough: 'Manhattan', slug: 'lower-east-side' },
  { name: 'East Village', borough: 'Manhattan', slug: 'east-village' },
  { name: 'Greenwich Village', borough: 'Manhattan', slug: 'greenwich-village' },
  { name: 'West Village', borough: 'Manhattan', slug: 'west-village' },
  { name: 'Chelsea', borough: 'Manhattan', slug: 'chelsea' },
  { name: 'Gramercy', borough: 'Manhattan', slug: 'gramercy' },
  { name: 'Flatiron', borough: 'Manhattan', slug: 'flatiron' },
  { name: 'Kips Bay', borough: 'Manhattan', slug: 'kips-bay' },
  { name: 'Murray Hill', borough: 'Manhattan', slug: 'murray-hill' },
  { name: 'Midtown', borough: 'Manhattan', slug: 'midtown' },
  { name: 'Hell\'s Kitchen', borough: 'Manhattan', slug: 'hells-kitchen' },
  { name: 'Times Square', borough: 'Manhattan', slug: 'times-square' },
  { name: 'Turtle Bay', borough: 'Manhattan', slug: 'turtle-bay' },
  { name: 'Upper East Side', borough: 'Manhattan', slug: 'upper-east-side' },
  { name: 'Upper West Side', borough: 'Manhattan', slug: 'upper-west-side' },
  { name: 'Morningside Heights', borough: 'Manhattan', slug: 'morningside-heights' },
  { name: 'Harlem', borough: 'Manhattan', slug: 'harlem' },
  { name: 'East Harlem', borough: 'Manhattan', slug: 'east-harlem' },
  { name: 'Washington Heights', borough: 'Manhattan', slug: 'washington-heights' },
  { name: 'Inwood', borough: 'Manhattan', slug: 'inwood' },
  { name: 'Hamilton Heights', borough: 'Manhattan', slug: 'hamilton-heights' },
  { name: 'Alphabet City', borough: 'Manhattan', slug: 'alphabet-city' },
  { name: 'NoHo', borough: 'Manhattan', slug: 'noho' },
  { name: 'Nolita', borough: 'Manhattan', slug: 'nolita' },
  { name: 'Two Bridges', borough: 'Manhattan', slug: 'two-bridges' },
  { name: 'Financial District', borough: 'Manhattan', slug: 'financial-district' },
  { name: 'Stuyvesant Town', borough: 'Manhattan', slug: 'stuyvesant-town' },
  { name: 'Roosevelt Island', borough: 'Manhattan', slug: 'roosevelt-island' },
  { name: 'Marble Hill', borough: 'Manhattan', slug: 'marble-hill' },

  // Brooklyn
  { name: 'Williamsburg', borough: 'Brooklyn', slug: 'williamsburg' },
  { name: 'Greenpoint', borough: 'Brooklyn', slug: 'greenpoint' },
  { name: 'Bushwick', borough: 'Brooklyn', slug: 'bushwick' },
  { name: 'Bedford-Stuyvesant', borough: 'Brooklyn', slug: 'bed-stuy' },
  { name: 'Crown Heights', borough: 'Brooklyn', slug: 'crown-heights' },
  { name: 'Park Slope', borough: 'Brooklyn', slug: 'park-slope' },
  { name: 'Prospect Heights', borough: 'Brooklyn', slug: 'prospect-heights' },
  { name: 'Fort Greene', borough: 'Brooklyn', slug: 'fort-greene' },
  { name: 'Brooklyn Heights', borough: 'Brooklyn', slug: 'brooklyn-heights' },
  { name: 'DUMBO', borough: 'Brooklyn', slug: 'dumbo' },
  { name: 'Downtown Brooklyn', borough: 'Brooklyn', slug: 'downtown-brooklyn' },
  { name: 'Boerum Hill', borough: 'Brooklyn', slug: 'boerum-hill' },
  { name: 'Cobble Hill', borough: 'Brooklyn', slug: 'cobble-hill' },
  { name: 'Carroll Gardens', borough: 'Brooklyn', slug: 'carroll-gardens' },
  { name: 'Red Hook', borough: 'Brooklyn', slug: 'red-hook' },
  { name: 'Gowanus', borough: 'Brooklyn', slug: 'gowanus' },
  { name: 'Sunset Park', borough: 'Brooklyn', slug: 'sunset-park' },
  { name: 'Bay Ridge', borough: 'Brooklyn', slug: 'bay-ridge' },
  { name: 'Dyker Heights', borough: 'Brooklyn', slug: 'dyker-heights' },
  { name: 'Bensonhurst', borough: 'Brooklyn', slug: 'bensonhurst' },
  { name: 'Coney Island', borough: 'Brooklyn', slug: 'coney-island' },
  { name: 'Brighton Beach', borough: 'Brooklyn', slug: 'brighton-beach' },
  { name: 'Sheepshead Bay', borough: 'Brooklyn', slug: 'sheepshead-bay' },
  { name: 'Gravesend', borough: 'Brooklyn', slug: 'gravesend' },
  { name: 'Marine Park', borough: 'Brooklyn', slug: 'marine-park' },
  { name: 'Midwood', borough: 'Brooklyn', slug: 'midwood' },
  { name: 'Flatbush', borough: 'Brooklyn', slug: 'flatbush' },
  { name: 'East Flatbush', borough: 'Brooklyn', slug: 'east-flatbush' },
  { name: 'Flatlands', borough: 'Brooklyn', slug: 'flatlands' },
  { name: 'Canarsie', borough: 'Brooklyn', slug: 'canarsie' },
  { name: 'East New York', borough: 'Brooklyn', slug: 'east-new-york' },
  { name: 'Brownsville', borough: 'Brooklyn', slug: 'brownsville' },
  { name: 'Clinton Hill', borough: 'Brooklyn', slug: 'clinton-hill' },
  { name: 'Prospect Lefferts Gardens', borough: 'Brooklyn', slug: 'prospect-lefferts-gardens' },
  { name: 'Windsor Terrace', borough: 'Brooklyn', slug: 'windsor-terrace' },
  { name: 'Ditmas Park', borough: 'Brooklyn', slug: 'ditmas-park' },
  { name: 'Kensington', borough: 'Brooklyn', slug: 'kensington' },
  { name: 'Borough Park', borough: 'Brooklyn', slug: 'borough-park' },
  { name: 'Bath Beach', borough: 'Brooklyn', slug: 'bath-beach' },

  // Queens
  { name: 'Long Island City', borough: 'Queens', slug: 'long-island-city' },
  { name: 'Astoria', borough: 'Queens', slug: 'astoria' },
  { name: 'Sunnyside', borough: 'Queens', slug: 'sunnyside' },
  { name: 'Woodside', borough: 'Queens', slug: 'woodside' },
  { name: 'Jackson Heights', borough: 'Queens', slug: 'jackson-heights' },
  { name: 'Elmhurst', borough: 'Queens', slug: 'elmhurst' },
  { name: 'Corona', borough: 'Queens', slug: 'corona' },
  { name: 'Flushing', borough: 'Queens', slug: 'flushing' },
  { name: 'Forest Hills', borough: 'Queens', slug: 'forest-hills' },
  { name: 'Rego Park', borough: 'Queens', slug: 'rego-park' },
  { name: 'Kew Gardens', borough: 'Queens', slug: 'kew-gardens' },
  { name: 'Richmond Hill', borough: 'Queens', slug: 'richmond-hill' },
  { name: 'Jamaica', borough: 'Queens', slug: 'jamaica' },
  { name: 'Ridgewood', borough: 'Queens', slug: 'ridgewood' },
  { name: 'Middle Village', borough: 'Queens', slug: 'middle-village' },
  { name: 'Maspeth', borough: 'Queens', slug: 'maspeth' },
  { name: 'Glendale', borough: 'Queens', slug: 'glendale' },
  { name: 'Ozone Park', borough: 'Queens', slug: 'ozone-park' },
  { name: 'Howard Beach', borough: 'Queens', slug: 'howard-beach' },
  { name: 'South Ozone Park', borough: 'Queens', slug: 'south-ozone-park' },
  { name: 'St. Albans', borough: 'Queens', slug: 'st-albans' },
  { name: 'Hollis', borough: 'Queens', slug: 'hollis' },
  { name: 'Queens Village', borough: 'Queens', slug: 'queens-village' },
  { name: 'Bellerose', borough: 'Queens', slug: 'bellerose' },
  { name: 'Bayside', borough: 'Queens', slug: 'bayside' },
  { name: 'Whitestone', borough: 'Queens', slug: 'whitestone' },
  { name: 'College Point', borough: 'Queens', slug: 'college-point' },
  { name: 'Douglaston', borough: 'Queens', slug: 'douglaston' },
  { name: 'Little Neck', borough: 'Queens', slug: 'little-neck' },
  { name: 'Auburndale', borough: 'Queens', slug: 'auburndale' },
  { name: 'Fresh Meadows', borough: 'Queens', slug: 'fresh-meadows' },
  { name: 'Briarwood', borough: 'Queens', slug: 'briarwood' },
  { name: 'Cambria Heights', borough: 'Queens', slug: 'cambria-heights' },
  { name: 'Rosedale', borough: 'Queens', slug: 'rosedale' },
  { name: 'Far Rockaway', borough: 'Queens', slug: 'far-rockaway' },
  { name: 'Rockaway Beach', borough: 'Queens', slug: 'rockaway-beach' },
  { name: 'Arverne', borough: 'Queens', slug: 'arverne' },
  { name: 'Breezy Point', borough: 'Queens', slug: 'breezy-point' },

  // Bronx
  { name: 'Mott Haven', borough: 'Bronx', slug: 'mott-haven' },
  { name: 'Hunts Point', borough: 'Bronx', slug: 'hunts-point' },
  { name: 'Longwood', borough: 'Bronx', slug: 'longwood' },
  { name: 'Melrose', borough: 'Bronx', slug: 'melrose' },
  { name: 'Morrisania', borough: 'Bronx', slug: 'morrisania' },
  { name: 'Highbridge', borough: 'Bronx', slug: 'highbridge' },
  { name: 'Concourse', borough: 'Bronx', slug: 'concourse' },
  { name: 'Fordham', borough: 'Bronx', slug: 'fordham' },
  { name: 'Bedford Park', borough: 'Bronx', slug: 'bedford-park' },
  { name: 'Norwood', borough: 'Bronx', slug: 'norwood' },
  { name: 'Kingsbridge', borough: 'Bronx', slug: 'kingsbridge' },
  { name: 'Riverdale', borough: 'Bronx', slug: 'riverdale' },
  { name: 'Fieldston', borough: 'Bronx', slug: 'fieldston' },
  { name: 'Spuyten Duyvil', borough: 'Bronx', slug: 'spuyten-duyvil' },
  { name: 'Marble Hill (Bronx)', borough: 'Bronx', slug: 'marble-hill-bronx' },
  { name: 'Throgs Neck', borough: 'Bronx', slug: 'throgs-neck' },
  { name: 'Country Club', borough: 'Bronx', slug: 'country-club' },
  { name: 'Pelham Bay', borough: 'Bronx', slug: 'pelham-bay' },
  { name: 'City Island', borough: 'Bronx', slug: 'city-island' },
  { name: 'Parkchester', borough: 'Bronx', slug: 'parkchester' },
  { name: 'Soundview', borough: 'Bronx', slug: 'soundview' },
  { name: 'Castle Hill', borough: 'Bronx', slug: 'castle-hill' },
  { name: 'Clason Point', borough: 'Bronx', slug: 'clason-point' },
  { name: 'Tremont', borough: 'Bronx', slug: 'tremont' },
  { name: 'Belmont', borough: 'Bronx', slug: 'belmont' },
  { name: 'Morris Heights', borough: 'Bronx', slug: 'morris-heights' },
  { name: 'University Heights', borough: 'Bronx', slug: 'university-heights' },
  { name: 'Woodlawn', borough: 'Bronx', slug: 'woodlawn' },
  { name: 'Wakefield', borough: 'Bronx', slug: 'wakefield' },
  { name: 'Williamsbridge', borough: 'Bronx', slug: 'williamsbridge' },
  { name: 'Eastchester', borough: 'Bronx', slug: 'eastchester' },
  { name: 'Co-op City', borough: 'Bronx', slug: 'co-op-city' },
  { name: 'Baychester', borough: 'Bronx', slug: 'baychester' },
  { name: 'Edenwald', borough: 'Bronx', slug: 'edenwald' },

  // Staten Island
  { name: 'St. George', borough: 'Staten Island', slug: 'st-george' },
  { name: 'Tompkinsville', borough: 'Staten Island', slug: 'tompkinsville' },
  { name: 'Stapleton', borough: 'Staten Island', slug: 'stapleton' },
  { name: 'Clifton', borough: 'Staten Island', slug: 'clifton' },
  { name: 'Port Richmond', borough: 'Staten Island', slug: 'port-richmond' },
  { name: 'West Brighton', borough: 'Staten Island', slug: 'west-brighton' },
  { name: 'New Brighton', borough: 'Staten Island', slug: 'new-brighton' },
  { name: 'Mariners Harbor', borough: 'Staten Island', slug: 'mariners-harbor' },
  { name: 'Arlington', borough: 'Staten Island', slug: 'arlington' },
  { name: 'Graniteville', borough: 'Staten Island', slug: 'graniteville' },
  { name: 'Willowbrook', borough: 'Staten Island', slug: 'willowbrook' },
  { name: 'New Springville', borough: 'Staten Island', slug: 'new-springville' },
  { name: 'Todt Hill', borough: 'Staten Island', slug: 'todt-hill' },
  { name: 'Dongan Hills', borough: 'Staten Island', slug: 'dongan-hills' },
  { name: 'South Beach', borough: 'Staten Island', slug: 'south-beach' },
  { name: 'Midland Beach', borough: 'Staten Island', slug: 'midland-beach' },
  { name: 'New Dorp', borough: 'Staten Island', slug: 'new-dorp' },
  { name: 'Oakwood', borough: 'Staten Island', slug: 'oakwood' },
  { name: 'Great Kills', borough: 'Staten Island', slug: 'great-kills' },
  { name: 'Eltingville', borough: 'Staten Island', slug: 'eltingville' },
  { name: 'Annadale', borough: 'Staten Island', slug: 'annadale' },
  { name: 'Huguenot', borough: 'Staten Island', slug: 'huguenot' },
  { name: 'Prince\'s Bay', borough: 'Staten Island', slug: 'princes-bay' },
  { name: 'Pleasant Plains', borough: 'Staten Island', slug: 'pleasant-plains' },
  { name: 'Tottenville', borough: 'Staten Island', slug: 'tottenville' },
  { name: 'Rossville', borough: 'Staten Island', slug: 'rossville' },
  { name: 'Charleston', borough: 'Staten Island', slug: 'charleston' },
  { name: 'Richmond Valley', borough: 'Staten Island', slug: 'richmond-valley' },
];

async function main() {
  console.log('Starting seed...');

  for (const neighborhood of neighborhoods) {
    await prisma.neighborhood.upsert({
      where: { slug: neighborhood.slug },
      update: {},
      create: neighborhood,
    });
  }

  console.log(`Seeded ${neighborhoods.length} neighborhoods`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
